apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prod-mbookmytrip-hpa
  namespace: prod-mbookmytrip
  labels:
    env: prod-mbookmytrip
    app: mbookmytrip
    layer: frontend
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mbookmytrip
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80